adding readme, main script, and requirements
stac-labs/tx_actionkit_vol_signups_to_van pull request #1
Opened 2022-08-01 16:11 UTC by KeshSridhar

### Your checklist for this pull request

- ☑︎ My code does not contain any secrets, API keys, or service accounts 
- ☑︎ My code does not commit any `.env` files
- ☑︎ I have tested my code locally to ensure it works 
- ☑︎ I am not logging `DEBUG` level AWS logs in my code

### Description :

Adding adding readme file, main.py, and requirements.txt for review, for TX Actionkit to VAN script

2022-08-01 17:31 UTC, bxjw requested changes
overall looks good. have some notes. i guess i'm undecided if this should be in the stac portal scripts repo or not, since it's ultra specific, so leave it here for now?

2022-08-01 17:31 UTC, bxjw commented on main.py
> +        zip = ""
more succinct syntax:
```
city = city or ""
state = state or ""
```
etc

2022-08-01 17:31 UTC, bxjw commented on main.py
> +    if phone != "" and email != "":
a more succinct version of all this would be to do the base payload as a dict and then add phones or emails as applicable. see https://github.com/stac-labs/stac-portal-scripts/blob/main/utilities/van.py for an example.

2022-08-03 02:02 UTC, KeshSridhar commented on main.py
> +    This function takes the Actionit data input, validates and formats for Find or Create VAN endpoint,
fixed

2022-08-03 02:02 UTC, KeshSridhar commented on main.py
> +    # However, I don't want to import the re module if I don't have to. This regex is also applicable to any
i added it

2022-08-03 02:02 UTC, KeshSridhar commented on main.py
> +        zip = ""
changed to this in validation methods

2022-08-03 02:05 UTC, KeshSridhar commented on main.py
> +    if phone != "" and email != "":
I went ahead and did a reverse of this, where i add all to payload, and since it's a dict, if no phones or no emails, I can just remove the key or keys.

Happy to change from this if needed , but seems concise?

2022-08-03 02:07 UTC, KeshSridhar reviewed
My code does not contain any secrets, API keys, or service accounts
 My code does not commit any .env files
 I have tested my code locally to ensure it works
 I am not logging DEBUG level AWS logs in my code

2022-08-03 11:13 UTC, bxjw approved these changes
looks good!

2022-08-03 11:29 UTC, merged